
parameters:
- name: isOfficialBuild
  type: boolean
  default: false
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging
- name: ApexAgentCleanup
  displayName: Delete or keep VS Apex test machine for debugging
  type: string
  default: delete
  values:
  - delete
  - stop
- name: NuGetLocalizationType
  displayName: Whether to do production-ready localization (Full), or pseudo-localization, aka PLOC, (Pseudo) for testing.
  type: string
  default: Full
  values:
  - Full
  - Pseudo
# - name: SourceBranch
#   displayName: Source Branch
#   type: string
#   default: $(replace(Resources.Pipeline.ComponentBuildUnderTest.sourceBranch,'refs/heads/',''))

resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: main
  - pipeline: nugetclientprivatedev
    source: NuGet.Client-PrivateDev
    trigger:
        branches:
          - dev-nkolev92-newPipeline
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

variables:
  DOTNET_NOLOGO: 1
  Codeql.Enabled: ${{ parameters.isOfficialBuild }}
  Codeql.TSAEnabled: ${{ parameters.isOfficialBuild }}

stages:
- stage: Initialize
  jobs:
  - job: GetSemanticVersion
    displayName: Get NuGet.Client semantic version
    timeoutInMinutes: 10
    pool:
      vmImage: windows-latest
    steps:
    - template: Initialize_Build_SemanticVersion.yml
    - task: DownloadPipelineArtifact@2
      displayName: "Download symbols - NonRTM artifact"
      inputs:
        source: 'specific'
        project: "devdiv"
        pipeline: "NuGet.Client-Official"
        artifact: "symbols - NonRTM"
        path: $(Pipeline.Workspace)\symbols\NonRTM
    - task: PowerShell@1
      displayName: "Print content in folder"
      inputs:
        scriptType: "inlineScript"
        inlineScript: |
          Get-ChildItem $(Pipeline.Workspace)\symbols\NonRTM

    - task: PowerShell@2
      displayName: 'Get Triggering Build Info'
      inputs:
        targetType: inline
        script: |
          Write-Host "Logging the metadata of the triggering build:"
          Write-Host "runName -- $(Resources.Pipeline.ComponentBuildUnderTest.runName)"
          Write-Host "runID -- $(Resources.Pipeline.ComponentBuildUnderTest.runID)"
          Write-Host "runURI -- $(Resources.Pipeline.ComponentBuildUnderTest.runURI)"
          Write-Host "sourceBranch -- $(Resources.Pipeline.ComponentBuildUnderTest.sourceBranch)"
          Write-Host "projectID -- $(Resources.Pipeline.ComponentBuildUnderTest.ProjectID)"
          Write-Host "pipelineID -- $(resources.pipeline.ComponentBuildUnderTest.pipelineID)"
          Write-Host "pipelineName -- $(resources.pipeline.ComponentBuildUnderTest.pipelineName)"
          Write-Host $(Pipeline.Workspace)/VS15/bootstrapper/8684543/f5f34b79-f107-43d4-b547-af3db489870a/vs_enterprise.exe



# Dartlab's template defines this in its own stage
- template: Apex_Tests_On_Windows.yml
  parameters:
    condition: "succeeded()"
    dependsOn:
      - Initialize
    variables:
      - name: VsBootstrapperUrl
        value: $(Pipeline.Workspace)/VS15/bootstrapper/8684543/f5f34b79-f107-43d4-b547-af3db489870a/vs_enterprise.exe
      - name: GitHubStatusName
        value: Daily Visual Studio Tests
      - name: RunSettingsURI
        value: $[dependencies.TestMachineConfiguration.outputs['SetRunSettingsURI.RunSettingsURI']]
    isOfficialBuild: ${{parameters.isOfficialBuild}}
    runSettingsURI: $(RunSettingsURI)
    dartLabEnvironment: ${{parameters.DartLabEnvironment}}
    testExecutionJobTimeoutInMinutes: 150
    bootstrapperUrl: $(VsBootstrapperUrl)
    testMachineCleanUpStrategy: ${{parameters.ApexAgentCleanup}}
    preTestMachineConfigurationStepList:
    - powershell : |
        try {
          $branchName = "$(resources.pipeline.ComponentBuildUnderTest.sourceBranch)"
          $branchName = $branchName.Replace('refs/heads/', '')

          $RunSettingsURI = "https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/NuGet-NuGet.Client-Trusted/$branchName/$(resources.pipeline.ComponentBuildUnderTest.runID);NuGet.Tests.Apex.runsettings"
          Write-Host "RunSettingsURI: $RunSettingsURI"
          # non-output variable for VS config in the configure machine job
          # output variable for test execution job
          Set-AzurePipelinesVariable 'RunSettingsURI' $RunSettingsURI
          Set-AzurePipelinesVariable -IsOutput 'RunSettingsURI' $RunSettingsURI
        }
        catch {
          Write-Host $_
          Write-Error "Failed to set SourceBranchName pipeline variable"
          throw
        }
      displayName: 'Set RunSettingsURI variable'
      name: SetRunSettingsURI

    - task: DownloadPipelineArtifact@2
      displayName: 'Download product NonRTM'
      continueOnError: true # in case build didn't publish this artifact
      inputs:
        buildType: specific
        project: $(resources.pipeline.ComponentBuildUnderTest.projectID)
        definition: $(resources.pipeline.ComponentBuildUnderTest.pipelineID)
        artifactName: 'VS15'
        Path: $(Pipeline.Workspace)/VS15
